version: '3'
services:
  blog-api:
    tty: true
    stdin_open: true
    build: .
    container_name: blog-api
    command: bash start.sh
    environment:
      RAILS_ENV: development
      APP_DB_HOST: db_blog-api
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db_blog-api
    links:
      - db_blog-api
    networks:
      - blog-api-net

  db_blog-api:
    container_name: db_blog-api
    image: postgres:10.5
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: root
    networks:
      - blog-api-net

networks:
  blog-api-net: